version: '3'

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'yojji'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - /var/lib/mysql